### ISSUE TITLE
dev-python/future should be in the RDEPEND of app-vim/youcompleteme

### ISSUE THREAD

**Issue by Universebenzene** [ahyangyi/ahyangyi-overlay#1]
If ycm run without python future module, it will get an error.

**Comment by Universebenzene** [comment]
是不是因为我英语太差了所以维护者不理我呢……
总之是youcompleteme运行的时候好像是依赖dev-python/future的，没装的话ycm会报错。是不是应该加到RDEPEND里比较好

**Comment by ahyangyi** [comment]
奇怪，为什么我一直没看到你的issue……

**Comment by ahyangyi** [comment]
好吧……我道歉，我不知道我做了什么，总之大概我的邮箱把github的提醒邮件给过滤了。
不过我查了一下，现在的ebuild里已经加上了这个依赖（大概是抄官方的更新的？）。
问题可以先关闭了。

**Comment by Universebenzene** [comment]
@ahyangyi 老哥你可能误会了啥……我说的是dev-python/future而不是dev-python/futures……差一个s，被要求的是不带s的那个
