### ISSUE TITLE
patch needed for recent commit of app-vim/youcompleteme

### ISSUE THREAD

**Issue by Universebenzene** [ahyangyi/ahyangyi-overlay#3]
好罢又是我来反馈ycm 😷……简单讲就是上游一个submodule某一个文件加了个python3.7的shebang，我没开~结果编译的时候就报错了……把那行删掉可以解决
直接打这个patch即可：http://fars.ee/TkhY

**Comment by Universebenzene** [comment]
我是不是真的烦到人家了……😷

**Comment by ahyangyi** [comment]
没有（但是为什么我昨晚真的清理掉了所有未读提醒，都没看到这一条？？？

**Comment by ahyangyi** [comment]
补丁(5840d17f0bce16f734b07a8adba1582b99515f3d)打上了（
